### ISSUE TITLE
Packing BFLIM crashes due to swizzle option

### ISSUE THREAD

**Issue by hlixed** [Tyulis/3DSkit#1]
`$ 3DSkit.py -p 'intro_bg_01.png' -o intro_bg_01.bflim -f BFLIM`
creates this error message:
```Packing...
Packing BFLIM
Traceback (most recent call last):
  File "3DSkit.py", line 163, in <module>
    pack_files(files, args.out, args.compression, args.format.upper(), args.big, opts)
  File "3DSkit.py", line 34, in pack_files
    outnames = pack.pack(filenames, output, format, endian, opts)
  File "3DSkit/pack/__init__.py", line 9, in pack
    func(*args)
  File "3DSkit/util/funcops.py", line 14, in __new__
    return self.main(*args, **kwargs)
  File "3DSkit/pack/BFLIM.py", line 77, in main
    img = self.swizzle(img, opts['swizzle'])
KeyError: 'swizzle'
```
Opts is an empty dict, so it has no `swizzle` option. Also, `self.swizzle` doesn't seem to be a function.

**Comment by Tyulis** [comment]
opts is the dict which contains the -O options, including, if they are specified,  swizzle and format for BFLIM. Here, the presence of the swizzle option was not checked... I fixed that and added better explainations on these format-specific options in the readme. Thanks for help!
