### ISSUE TITLE
Mini repacking: "3DSkit is currently unable to pack this format"

### ISSUE THREAD

**Issue by PP-theSLAYER** [Tyulis/3DSkit#11]
Using 3DSkit, I managed to unpack a .bin file which is actually a BL mini format archive.
(command line: 3DSkit.py -x 0.bin)

However, the tool doesn't allow repacking, with that error message thrown.
I confirm that the mini.py is indeed in the "pack" folder.

As I'm trying to pack a directory of files, command line used is:
3DSkit.py -pdvf mini 0                (0 being the folder; I understand without options, it'll default to BL)

I've tried playing around with the command line, and can't get it to work, so it *might* be a bug.
(assuming it's not an error on my side; I've managed to get sarc packing, garc packing, bflim injecting to work, so this is the only thing that bugs me on my end)

**Comment by Tyulis** [comment]
It's indeed a bug, I fix it ASAP. Thanks for help!

**Comment by Tyulis** [comment]
It should be fixed in the latest commit.

**Comment by PP-theSLAYER** [comment]
Thank you :D

**Comment by Tyulis** [comment]
No problem
