### ISSUE TITLE
No support for unpacking BFFNT v4.1

### ISSUE THREAD

**Issue by Martin005** [Tyulis/3DSkit#13]
There is no support for unpacking BFFNT version 4.1.0. This version can be found in Super Mario Odyssey.

Here is included one example font:
[NumberFont26.zip](https://github.com/Tyulis/3DSkit/files/2144931/NumberFont26.zip)

Here is the same font but extracted as png (credits to Random Talking Bush and SciresM - https://www.spriters-resource.com/nintendo_switch/supermarioodyssey/sheet/103323/):
![numberfont26_23x31](https://user-images.githubusercontent.com/10096404/42029830-1b848f68-7ad1-11e8-81aa-f40e364534f4.png)

**Comment by Tyulis** [comment]
OK, I'll try to take a look to it

**Comment by Tyulis** [comment]
Huh... Your file is a BFFNT built around a BNTX texture. That's quite weird.

**Comment by Martin005** [comment]
I have actually found a QuickBMS script for "BNTX, BFRES and BFFNT to DDS" specifically for the Switch (if that helps) - https://mega.nz/#!mhxUgD6T!S1De3dz3VsoHyoDc8ecNfhW0eZRoIOPDdHhLK9fDMu0.

It was originally posted by the aforementioned Random Talking Bush - https://www.vg-resource.com/thread-29836.html

**Comment by Tyulis** [comment]
I added support for this, and BC4 textures. The result is reversed, it may be for hardware optimisation, I'll search if there is something in the file to detect that. Waiting for it, a few seconds in any image editor can solve the problem.

**Comment by Martin005** [comment]
@Tyulis I cannot see any commits in regards of this, could you please check that?

**Comment by Tyulis** [comment]
Huh... I though that I pushed it, sorry.
