### ISSUE TITLE
Error unpacking ALYT files

### ISSUE THREAD

**Issue by dgyst** [Tyulis/3DSkit#29]
When unpacking alyt archive I get an error. There is no such problem with other alyt archives. Help me to solve the problem. I attach the file with the problem.
[dec_7.zip](https://github.com/Tyulis/3DSkit/files/12916247/dec_7.zip)

**Comment by Tyulis** [comment]
Fixed, just a strange dummy entry format

**Comment by dgyst** [comment]
Thx!
