### ISSUE TITLE
BFLIM unpacking/repacking of non-multiple of 8px images results in weirdly distorted images

### ISSUE THREAD

**Issue by hlixed** [Tyulis/3DSkit#9]
(Firstly, unpacking an alyt file seems to produce two folders: one `x` folder containing the __alyt__ folder, and one `x_` folder with the `timg` and other folders.)

I've downloaded this nice cat off the internet to serve as a test image (downscaled here).
![testcat](https://user-images.githubusercontent.com/12309977/33020162-31630df4-cdcb-11e7-8675-5cc23bbe9bc9.png)

I then packed it into a BFLIM:
`python3 3DSkit.py -p testcat.png -f BFLIM -o testcat_packed.bflim`
and took it back out again:
`python3 3DSkit.py -x testcat_packed.bflim`

However, in the process, 3DSkit horribly mangled this poor kitty. You wouldn't want to leave this poor innocent kitty like this, would you?
![testcat_new](https://user-images.githubusercontent.com/12309977/33020208-6161d5bc-cdcb-11e7-962d-493ae7b99ac7.png)

However, I've noticed this doesn't happen with all images: This quick test Kirby, for example, passes through extraction and repacking just fine. (excuse his appearance; he only had a few seconds to compose himself)
![lunasol_edited3](https://user-images.githubusercontent.com/12309977/33020561-d8c369f8-cdcc-11e7-954e-c149d2e58b88.png)
![lunasol_edited2](https://user-images.githubusercontent.com/12309977/33020582-ed7babbc-cdcc-11e7-8145-e4ee771b8885.png)

Do you know why this might be happening? Is it something to do with the dimensions of the image?

**Comment by Tyulis** [comment]
Yep, poor kitty. Another problem in BFLIMs. That's at least the fourth like that. I'll try to determine what it is. And for the first bug, it should be fixed in my next commit. Another time, thanks for help!

**Comment by Tyulis** [comment]
Problem found! Unlike the Kirby's one, the cat's frame has not a multiple of 8 width, so the last 8x8 tile of each line is not properly processed. Now, it only remains to find where the problem comes from...

**Comment by Tyulis** [comment]
I lazily avoided the problem by adding a few pixels to the image to get a multiple of 8 pixels widths. Now it should work better. This cat is saved!

**Comment by hlixed** [comment]
Ha, I had just discovered that this produces a glitchy mess only when either the width or height of the input image isn't a multiple of 8, and came here to report it. Glad to see you found it first! It might be worth printing a message such as "Texture dimensions not a multiple of 8, padding to nearest multiple" just to inform the users what's going on.
Thanks for saving the cat!

**Comment by hlixed** [comment]
I'm not sure this really solves the problem, though, because there are bflims in USUM that contain non-multiple-of-8 sizes, such as 180x300. They extract fine, so clearly they're valid, and they had to have been created somehow. It probably works for now, but it's still worth figuring out how the standard works for non-8-multiple images IMO.

**Comment by Tyulis** [comment]
I have not fixed the problem, it's an hacky workaround - if I really find the problem someday, I'll try to fix it, but i searched 2 hours long and i didn't find the bug.
